FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir kafka-python==2.0.2

COPY kafka/ /app/kafka/

ENV KAFKA_BOOTSTRAP_SERVERS=kafka:29092 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

ENTRYPOINT ["python", "/app/kafka/traffic_ingestion.py"]
